wm: Fix Launcher3 NPE
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.wm.Task.lambda$applyAnimationUnchecked$13(Task.java:3355)

Change-Id: I57c2b3874ed3282dccaa109dd7a733332a3681f0
Signed-off-by: Richard Raya <rdxzv.dev@gmail.com>